### ISSUE TITLE
gensim_fasttext.mod文件如何生成

### ISSUE THREAD

**Issue by Lireanstar** [coranholmes/pt_chatbot#2]
gensim_fasttext.mod如何生成的呢？
我现在正在用小黄鸡的语料进行测试，请问gensim_fasttext.mod是什么文件？自己训练的吗
哪里有相关的训练代码或者训练好的模型的下载地址？

**Comment by coranholmes** [comment]
> 
> 
> gensim_fasttext.mod如何生成的呢？
> 我现在正在用小黄鸡的语料进行测试，请问gensim_fasttext.mod是什么文件？自己训练的吗
> 哪里有相关的训练代码或者训练好的模型的下载地址？

如果不需要载入预训练的向量的话这个不用管，把`embeddingFile`设置为`None`即可。
如果需要载入预训练的向量的话，在`compute_sent_emb.py`的最开始几行注释解释了一下`gensim_fasttext.mod`是将gensim导入fastText的结果用pickle的方式保存了一下。主要原因是gensim对fastText支持的不是很好，如果每次都使用`load_word2vec_format`载入太慢了，所以载入一次用pickle存下来，下次用pickle读入速度会快点。
另外，我更新了一下检索模型部分的`README`，你可以看一下。

**Comment by Lireanstar** [comment]
Thx,
